version: "3.9"
services:

  ugc-service-test-node-1:
    image: mongo:7.0.0-rc8
    container_name: ugc-service-test-node-1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - ugc-service-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 27017:27017

  ugc-service-mongo-express:
    image: mongo-express
    container_name: ugc-service-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@ugc-service-test-node-1:27017/
    platform: linux/amd64
    depends_on:
      ugc-service-test-node-1:
        condition: service_healthy
    networks:
      - ugc-service-network

networks:
  ugc-service-network:
    driver: bridge
    external: true
    name: ugc-service-network
