repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: flake8
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m flake8
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        description: mypy
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m mypy
        args: ["--config-file=./mypy.ini"]
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: black
        name: black
        description: black
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m black
        language: python
        types: [python]

-   repo: local
    hooks:
    -   id: isort
        name: isort
        description: isort
        entry: env -i PATH=./bin:./.venv/bin:./venv/bin python3 -m isort
        language: python
        types: [python]
