version: '3.8'

services:

  ugc-service-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./infra/nginx/configs:/etc/nginx/conf.d:rw

  ugc-service-api:
    ports:
      - ${BACKEND_PORT:-8001}:8001
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    volumes:
      - ./src/app:/opt/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  ugc-service-etl:
    volumes:
      - ./src/etl:/opt/etl

  ugc-service-redis:
    ports:
      - ${REDIS_PORT:-6379}:6379
