version: '3.7'

services:

  ugc-service-filebeat:
    build:
      context: infra/filebeat/.
      args:
        STACK_VERSION: ${STACK_VERSION}
    user: root
    volumes:
      - ./infra/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - movies-elk-network
      - ugc-service-network
    env_file:
      - ./.env

networks:
  movies-elk-network:
    external: true
  ugc-service-network:
    external: true
