openapi: 3.0.3
info:
  title: UGC-service
  description: Описание для endpoint'ов ugc сервиса
  version: 0.1.0
tags:
  - name: ratings
    description: Оценки фильмов
  - name: reviews
    description: Рецензии к фильмам
  - name: favorites
    description: Закладки
paths:
  /ratings:
    get:
      tags:
        - ratings
      summary: Показать оценённые фильмы для авторизованного пользователя
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayRating'
        '401':
          description: Unauthorized
      security:
        - access_key: []
  /ratings/{film_id}:
    get:
      tags:
        - ratings
      summary: Показать оценку фильма для авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
    post:
      tags:
        - ratings
      summary: Оценить фильм авторизованному пользователю
      description: Добавляет оценку к фильму от 0 до 10
      parameters:
        - $ref: '#/components/parameters/FilmId'
        - $ref: '#/components/parameters/Rate'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '409':
          description: Conflict
      security:
        - access_key: []
    patch:
      tags:
        - ratings
      summary: Изменить оценку фильма для авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
        - $ref: '#/components/parameters/Rate'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
    delete:
      tags:
        - ratings
      summary: Удалить оценку фильма для авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
  /ratings/{film_id}/info:
    get:
      tags:
        - ratings
      summary: Показать количество оценок и среднюю оценку фильма
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatingInfo'
        '404':
          description: Not Found
  /favorites:
    get:
      tags:
        - favorites
      summary: Показать закладки авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayFavorites'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
  /favorites/{film_id}:
    get:
      tags:
        - favorites
      summary: Показать закладку авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Favorite'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
    post:
      tags:
        - favorites
      summary: Добавить фильм в закладки для авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '409':
          description: Conflict
      security:
        - access_key: []
    delete:
      tags:
        - favorites
      summary: Удалить фильм из закладок для авторизованного пользователя
      parameters:
        - $ref: '#/components/parameters/FilmId'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - access_key: []
components:
  schemas:
    RatingInfo:
      type: object
      properties:
        count:
          type: integer
          example: 155
        average:
          type: number
          format: float
          example: 102.14
      required:
        - count
        - average
    Rating:
      type: object
      properties:
        rating_id:
          type: string
          format: uuid
          example: '8dcb2a02-7892-483d-9269-c8d583ffc8c4'
        film_id:
          type: string
          format: uuid
          example: '1eae720b-0121-47b6-ab3a-b4cf96f08370'
        rating:
          type: integer
          example: 10
      required:
        - rating_id
        - film_id
        - rating
    ArrayRating:
      type: array
      items:
        $ref: '#/components/schemas/Rating'
    Favorite:
      type: object
      properties:
        favorite_id:
          type: string
          format: uuid
          example: '1eae720b-0121-47b6-ab3a-b4cf96f08370'
        film_id:
          type: string
          format: uuid
          example: '1eae720b-0121-47b6-ab3a-b4cf96f08370'
      required:
        - favorite_id
        - film_id
    ArrayFavorites:
      type: array
      items:
        $ref: '#/components/schemas/Favorite'
  parameters:
    FilmId:
      name: film_id
      in: path
      description: UUID фильма
      required: true
      schema:
        type: string
        format: uuid
    UserId:
      name: user_id
      in: path
      description: UUID фильма
      required: true
      schema:
        type: string
        format: uuid
    Rate:
      name: rate
      in: query
      description: Оценка фильма
      schema:
        type: integer
        minimum: 0
        maximum: 10
      required: true
  securitySchemes:
    access_key:
      type: apiKey
      in: header
      name: Authorization