name: ${FILEBEAT_HOST}

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

http:
  enabled: true
  host: 0.0.0.0

filebeat:
  autodiscover.providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: ugc-service-nginx
          config:
            - module: nginx
              access:
                input:
                  type: container
                  paths:
                    - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
                  json.keys_under_root: true
                  json.keys_under_root: true
                  tags: ["nginx-access"]
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: ugc-service-api
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              json.keys_under_root: true
              json.keys_under_root: true
              tags: ["ugc-service"]

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}:5045"]
