name: ${FILEBEAT_HOST}

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

http:
  enabled: true
  host: 0.0.0.0

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/ugc_service/*.json
  fields:
    - service: ugc-service
  tags: ["ugc-service"]
  json:
    keys_under_root: true
    add_error_key: true
- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.json
  tags: ["nginx-access"]
  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}:5045"]
