name: Deploy Images to GHCR
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
    - name: 'Clone code'
      uses: actions/checkout@v3

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build Inventory Image'
      run: |
        docker build . --file ./infra/backend/Dockerfile --tag ghcr.io/team21-movies-services/ugc-service:latest
        docker push ghcr.io/team21-movies-services/ugc-service:latest
